# Auto-generated by compose2nix.

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."arrs-gluetun" = {
    image = "qmcgaw/gluetun";
    environment = {
      "SERVER_COUNTRIES" = "Canada,Iceland";
      "VPN_SERVICE_PROVIDER" = "protonvpn";
    };
    environmentFiles = [
      config.sops.secrets."arr/gluetun.env".path
    ];
    ports = [
      "8112:8112/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
      "8989:8989/tcp"
      "7878:7878/tcp"
      "5055:5055/tcp"
      "9696:9696/tcp"
      "8686:8686/tcp" # Lidarr
      "5000:5000/tcp" # Lidatube
    ];
    labels = {
      "compose2nix.settings.sops.secrets" = "arr/gluetun.env";
    };
    log-driver = "journald";
    extraOptions = [
      "--cap-add=NET_ADMIN"
      "--device=/dev/net/tun:/dev/net/tun:rwm"
      "--network-alias=gluetun"
      "--network=arrs_default"
    ];
    user = "root:root";
  };
  systemd.services."podman-arrs-gluetun" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-arrs_default.service"
    ];
    requires = [
      "podman-network-arrs_default.service"
    ];
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  /*virtualisation.oci-containers.containers."audiobookrequest" = {
    image = "markbeep/audiobookrequest:1";
    environment = {
      "ABR_APP__FORCE_LOGIN_TYPE" = "forms";
      "ABR_APP__PORT" = "5432";
    };
    volumes = [
      "/shared/systems/services/arr/audiobookrequest:/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
      "radarr"
      "sonarr"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
  };
  systemd.services."podman-audiobookrequest" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };*/
  virtualisation.oci-containers.containers."deluge" = {
    image = "lscr.io/linuxserver/deluge:latest";
    environment = {
      "DELUGE_LOGLEVEL" = "error";
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/systems/services/arr/deluge/config:/config:rw"
      "/shared/systems/services/arr/deluge/downloads:/downloads:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-deluge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "ghcr.io/fallenbagel/jellyseerr:latest";
    environment = {
      "LOG_LEVEL" = "debug";
      "PORT" = "5055";
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/systems/services/arr/jellyseerr:/app/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
      "radarr"
      "sonarr"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1"
      "--health-interval=15s"
      "--health-retries=3"
      "--health-start-period=20s"
      "--health-timeout=3s"
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-jellyseerr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/systems/services/arr/prowlarr:/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."radarr" = {
    image = "lscr.io/linuxserver/radarr:latest";
    environment = {
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/data/media/Movies:/movies:rw"
      "/shared/systems/services/arr/deluge/downloads:/downloads:rw"
      "/shared/systems/services/arr/radarr:/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-radarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/data/media/Shows:/tv:rw"
      "/shared/systems/services/arr/deluge/downloads:/downloads:rw"
      "/shared/systems/services/arr/sonarr:/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lidarr" = {
    image = "lscr.io/linuxserver/lidarr:latest";
    environment = {
      "TZ" = "America/New_York";
    };
    volumes = [
      "/shared/data/media/Music:/music:rw"
      "/shared/systems/services/arr/deluge/downloads:/downloads:rw"
      "/shared/systems/services/arr/lidarr:/config:rw"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
      "lidatube"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-lidarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lidatube" = {
    image = "thewicklowwolf/lidatube:latest";
    environment = {
      PUID = "0";
      PGID = "0";
      lidarr_address = "https://lid.arr.dax.gay";
      thread_limit = "8";
      sync_schedule = "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23";
      attempt_lidarr_import = "True";
    };
    volumes = [
      "/shared/systems/services/arr/deluge/downloads:/lidatube/downloads:rw"
      "/shared/systems/services/arr/lidatube:/lidatube/config:rw"
      "/etc/localtime:/etc/localtime:ro"
    ];
    dependsOn = [
      "arrs-gluetun"
      "deluge"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network=container:arrs-gluetun"
    ];
    user = "root:root";
  };
  systemd.services."podman-lidatube" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-arrs-root.target"
    ];
    wantedBy = [
      "podman-compose-arrs-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-arrs_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f arrs_default";
    };
    script = ''
      podman network inspect arrs_default || podman network create arrs_default
    '';
    partOf = [ "podman-compose-arrs-root.target" ];
    wantedBy = [ "podman-compose-arrs-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-arrs-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
